*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMK_VIEW_PARTNER................................*
FORM GET_DATA_ZMK_VIEW_PARTNER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM SBUSPART WHERE
(VIM_WHERETAB) .
    CLEAR ZMK_VIEW_PARTNER .
ZMK_VIEW_PARTNER-MANDANT =
SBUSPART-MANDANT .
ZMK_VIEW_PARTNER-BUSPARTNUM =
SBUSPART-BUSPARTNUM .
ZMK_VIEW_PARTNER-CONTACT =
SBUSPART-CONTACT .
ZMK_VIEW_PARTNER-CONTPHONO =
SBUSPART-CONTPHONO .
ZMK_VIEW_PARTNER-BUSPATYP =
SBUSPART-BUSPATYP .
    SELECT SINGLE * FROM STRAVELAG WHERE
AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC EQ 0.
ZMK_VIEW_PARTNER-AGENCYNUM =
STRAVELAG-AGENCYNUM .
ZMK_VIEW_PARTNER-NAME =
STRAVELAG-NAME .
ZMK_VIEW_PARTNER-STREET =
STRAVELAG-STREET .
ZMK_VIEW_PARTNER-POSTBOX =
STRAVELAG-POSTBOX .
ZMK_VIEW_PARTNER-POSTCODE =
STRAVELAG-POSTCODE .
ZMK_VIEW_PARTNER-CITY =
STRAVELAG-CITY .
ZMK_VIEW_PARTNER-COUNTRY =
STRAVELAG-COUNTRY .
ZMK_VIEW_PARTNER-REGION =
STRAVELAG-REGION .
ZMK_VIEW_PARTNER-TELEPHONE =
STRAVELAG-TELEPHONE .
    ENDIF.
<VIM_TOTAL_STRUC> = ZMK_VIEW_PARTNER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMK_VIEW_PARTNER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMK_VIEW_PARTNER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMK_VIEW_PARTNER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM SBUSPART WHERE
  BUSPARTNUM = ZMK_VIEW_PARTNER-BUSPARTNUM .
    IF SY-SUBRC = 0.
    DELETE SBUSPART .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM STRAVELAG WHERE
    AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC = 0.
    DELETE STRAVELAG .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM SBUSPART WHERE
  BUSPARTNUM = ZMK_VIEW_PARTNER-BUSPARTNUM .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR SBUSPART.
    ENDIF.
SBUSPART-MANDANT =
ZMK_VIEW_PARTNER-MANDANT .
SBUSPART-BUSPARTNUM =
ZMK_VIEW_PARTNER-BUSPARTNUM .
SBUSPART-CONTACT =
ZMK_VIEW_PARTNER-CONTACT .
SBUSPART-CONTPHONO =
ZMK_VIEW_PARTNER-CONTPHONO .
SBUSPART-BUSPATYP =
ZMK_VIEW_PARTNER-BUSPATYP .
    IF SY-SUBRC = 0.
    UPDATE SBUSPART ##WARN_OK.
    ELSE.
    INSERT SBUSPART .
    ENDIF.
    SELECT SINGLE FOR UPDATE * FROM STRAVELAG WHERE
    AGENCYNUM = SBUSPART-BUSPARTNUM .
      IF SY-SUBRC <> 0.   "insert preprocessing: init WA
        CLEAR STRAVELAG.
STRAVELAG-AGENCYNUM =
SBUSPART-BUSPARTNUM .
      ENDIF.
STRAVELAG-AGENCYNUM =
ZMK_VIEW_PARTNER-AGENCYNUM .
STRAVELAG-NAME =
ZMK_VIEW_PARTNER-NAME .
STRAVELAG-STREET =
ZMK_VIEW_PARTNER-STREET .
STRAVELAG-POSTBOX =
ZMK_VIEW_PARTNER-POSTBOX .
STRAVELAG-POSTCODE =
ZMK_VIEW_PARTNER-POSTCODE .
STRAVELAG-CITY =
ZMK_VIEW_PARTNER-CITY .
STRAVELAG-COUNTRY =
ZMK_VIEW_PARTNER-COUNTRY .
STRAVELAG-REGION =
ZMK_VIEW_PARTNER-REGION .
STRAVELAG-TELEPHONE =
ZMK_VIEW_PARTNER-TELEPHONE .
    IF SY-SUBRC = 0.
    UPDATE STRAVELAG ##WARN_OK.
    ELSE.
    INSERT STRAVELAG .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMK_VIEW_PARTNER-UPD_FLAG,
STATUS_ZMK_VIEW_PARTNER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMK_VIEW_PARTNER.
  SELECT SINGLE * FROM SBUSPART WHERE
BUSPARTNUM = ZMK_VIEW_PARTNER-BUSPARTNUM .
ZMK_VIEW_PARTNER-MANDANT =
SBUSPART-MANDANT .
ZMK_VIEW_PARTNER-BUSPARTNUM =
SBUSPART-BUSPARTNUM .
ZMK_VIEW_PARTNER-CONTACT =
SBUSPART-CONTACT .
ZMK_VIEW_PARTNER-CONTPHONO =
SBUSPART-CONTPHONO .
ZMK_VIEW_PARTNER-BUSPATYP =
SBUSPART-BUSPATYP .
    SELECT SINGLE * FROM STRAVELAG WHERE
AGENCYNUM = SBUSPART-BUSPARTNUM .
    IF SY-SUBRC EQ 0.
ZMK_VIEW_PARTNER-AGENCYNUM =
STRAVELAG-AGENCYNUM .
ZMK_VIEW_PARTNER-NAME =
STRAVELAG-NAME .
ZMK_VIEW_PARTNER-STREET =
STRAVELAG-STREET .
ZMK_VIEW_PARTNER-POSTBOX =
STRAVELAG-POSTBOX .
ZMK_VIEW_PARTNER-POSTCODE =
STRAVELAG-POSTCODE .
ZMK_VIEW_PARTNER-CITY =
STRAVELAG-CITY .
ZMK_VIEW_PARTNER-COUNTRY =
STRAVELAG-COUNTRY .
ZMK_VIEW_PARTNER-REGION =
STRAVELAG-REGION .
ZMK_VIEW_PARTNER-TELEPHONE =
STRAVELAG-TELEPHONE .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMK_VIEW_PARTNER-AGENCYNUM .
      CLEAR ZMK_VIEW_PARTNER-NAME .
      CLEAR ZMK_VIEW_PARTNER-STREET .
      CLEAR ZMK_VIEW_PARTNER-POSTBOX .
      CLEAR ZMK_VIEW_PARTNER-POSTCODE .
      CLEAR ZMK_VIEW_PARTNER-CITY .
      CLEAR ZMK_VIEW_PARTNER-COUNTRY .
      CLEAR ZMK_VIEW_PARTNER-REGION .
      CLEAR ZMK_VIEW_PARTNER-TELEPHONE .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMK_VIEW_PARTNER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMK_VIEW_PARTNER-BUSPARTNUM TO
SBUSPART-BUSPARTNUM .
MOVE ZMK_VIEW_PARTNER-MANDANT TO
SBUSPART-MANDANT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SBUSPART'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SBUSPART TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SBUSPART'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

MOVE SBUSPART-BUSPARTNUM TO
STRAVELAG-AGENCYNUM .
MOVE ZMK_VIEW_PARTNER-MANDANT TO
STRAVELAG-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'STRAVELAG'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN STRAVELAG TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'STRAVELAG'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
