*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMK_PLVW_SPFLI..................................*
FORM GET_DATA_ZMK_PLVW_SPFLI.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM SPFLI WHERE
(VIM_WHERETAB) .
    CLEAR ZMK_PLVW_SPFLI .
ZMK_PLVW_SPFLI-MANDT =
SPFLI-MANDT .
ZMK_PLVW_SPFLI-CARRID =
SPFLI-CARRID .
ZMK_PLVW_SPFLI-CONNID =
SPFLI-CONNID .
ZMK_PLVW_SPFLI-COUNTRYFR =
SPFLI-COUNTRYFR .
ZMK_PLVW_SPFLI-CITYFROM =
SPFLI-CITYFROM .
ZMK_PLVW_SPFLI-AIRPFROM =
SPFLI-AIRPFROM .
ZMK_PLVW_SPFLI-COUNTRYTO =
SPFLI-COUNTRYTO .
ZMK_PLVW_SPFLI-CITYTO =
SPFLI-CITYTO .
ZMK_PLVW_SPFLI-AIRPTO =
SPFLI-AIRPTO .
    SELECT SINGLE * FROM SCARR WHERE
CARRID = SPFLI-CARRID .
    IF SY-SUBRC EQ 0.
    ENDIF.
<VIM_TOTAL_STRUC> = ZMK_PLVW_SPFLI.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMK_PLVW_SPFLI .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMK_PLVW_SPFLI.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMK_PLVW_SPFLI-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM SPFLI WHERE
  CARRID = ZMK_PLVW_SPFLI-CARRID AND
  CONNID = ZMK_PLVW_SPFLI-CONNID .
    IF SY-SUBRC = 0.
    DELETE SPFLI .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM SPFLI WHERE
  CARRID = ZMK_PLVW_SPFLI-CARRID AND
  CONNID = ZMK_PLVW_SPFLI-CONNID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR SPFLI.
    ENDIF.
SPFLI-MANDT =
ZMK_PLVW_SPFLI-MANDT .
SPFLI-CARRID =
ZMK_PLVW_SPFLI-CARRID .
SPFLI-CONNID =
ZMK_PLVW_SPFLI-CONNID .
SPFLI-COUNTRYFR =
ZMK_PLVW_SPFLI-COUNTRYFR .
SPFLI-CITYFROM =
ZMK_PLVW_SPFLI-CITYFROM .
SPFLI-AIRPFROM =
ZMK_PLVW_SPFLI-AIRPFROM .
SPFLI-COUNTRYTO =
ZMK_PLVW_SPFLI-COUNTRYTO .
SPFLI-CITYTO =
ZMK_PLVW_SPFLI-CITYTO .
SPFLI-AIRPTO =
ZMK_PLVW_SPFLI-AIRPTO .
    IF SY-SUBRC = 0.
    UPDATE SPFLI ##WARN_OK.
    ELSE.
    INSERT SPFLI .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMK_PLVW_SPFLI-UPD_FLAG,
STATUS_ZMK_PLVW_SPFLI-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMK_PLVW_SPFLI.
  SELECT SINGLE * FROM SPFLI WHERE
CARRID = ZMK_PLVW_SPFLI-CARRID AND
CONNID = ZMK_PLVW_SPFLI-CONNID .
ZMK_PLVW_SPFLI-MANDT =
SPFLI-MANDT .
ZMK_PLVW_SPFLI-CARRID =
SPFLI-CARRID .
ZMK_PLVW_SPFLI-CONNID =
SPFLI-CONNID .
ZMK_PLVW_SPFLI-COUNTRYFR =
SPFLI-COUNTRYFR .
ZMK_PLVW_SPFLI-CITYFROM =
SPFLI-CITYFROM .
ZMK_PLVW_SPFLI-AIRPFROM =
SPFLI-AIRPFROM .
ZMK_PLVW_SPFLI-COUNTRYTO =
SPFLI-COUNTRYTO .
ZMK_PLVW_SPFLI-CITYTO =
SPFLI-CITYTO .
ZMK_PLVW_SPFLI-AIRPTO =
SPFLI-AIRPTO .
    SELECT SINGLE * FROM SCARR WHERE
CARRID = SPFLI-CARRID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMK_PLVW_SPFLI USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMK_PLVW_SPFLI-CARRID TO
SPFLI-CARRID .
MOVE ZMK_PLVW_SPFLI-CONNID TO
SPFLI-CONNID .
MOVE ZMK_PLVW_SPFLI-MANDT TO
SPFLI-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'SPFLI'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN SPFLI TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'SPFLI'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMK_PLVW_SPFLI USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
SPFLI-MANDT =
ZMK_PLVW_SPFLI-MANDT .
SPFLI-CARRID =
ZMK_PLVW_SPFLI-CARRID .
SPFLI-CONNID =
ZMK_PLVW_SPFLI-CONNID .
SPFLI-COUNTRYFR =
ZMK_PLVW_SPFLI-COUNTRYFR .
SPFLI-CITYFROM =
ZMK_PLVW_SPFLI-CITYFROM .
SPFLI-AIRPFROM =
ZMK_PLVW_SPFLI-AIRPFROM .
SPFLI-COUNTRYTO =
ZMK_PLVW_SPFLI-COUNTRYTO .
SPFLI-CITYTO =
ZMK_PLVW_SPFLI-CITYTO .
SPFLI-AIRPTO =
ZMK_PLVW_SPFLI-AIRPTO .
    SELECT SINGLE * FROM SCARR WHERE
CARRID = SPFLI-CARRID .
    IF SY-SUBRC EQ 0.
    ELSE.
      CLEAR SY-SUBRC.
    ENDIF.
ENDFORM.
